name: buoy
channels:
  - conda-forge
dependencies:
  # python/env dependencies
  - python=3.14.6
  - pip
  - uv=0.11.21
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  - python-ligo-lw
